# Generated by Django 4.2.5 on 2023-10-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'Admin'), (1, 'Board'), (2, 'Employee'), (3, 'Other')], default=3, help_text='User Privilege Level'),
        ),
    ]
