# Generated by Django 4.2.5 on 2023-10-10 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fileshare.utilities
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='File Name (Do not enter file extension here)', max_length=200)),
                ('ext', models.CharField(blank=True, help_text='File Extension', max_length=10)),
                ('size', models.FloatField(blank=True, default=0)),
                ('file_instance', models.FileField(help_text='Upload the file here', max_length=1000, null=True, upload_to=fileshare.utilities.get_file_upload_path, verbose_name='File')),
                ('expiration', models.DateTimeField(blank=True, default=fileshare.utilities.get_file_expiration_date, help_text='Files will be deleted after this date.', verbose_name='File expiration')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='organization.organization')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Files',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
