# Generated by Django 4.2.5 on 2023-10-18 19:31

from django.db import migrations, models
import fileshare.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_fileshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='unique_code',
            field=models.CharField(default=fileshare.utilities.get_unique_code, help_text='Unique code used for creating sharing links', max_length=50, unique=True),
        ),
    ]
